### ISSUE TITLE
TODO: add `globalThis` for modern browsers and `self` for web workers in older browsers

### ISSUE THREAD

**Issue by chee** [Financial-Times/oax#16]
TODO: add `globalThis` for modern browsers and `self` for web workers in older browsers

_Originally posted by @JakeChampion in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzUwMDA3MDA0/pull_requests/unread_timeline_

**Comment by JakeChampion** [comment]
After further investigation @chee and myself think we can remove `global` from head.js and remove the argument `typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this` in tail.js

```bash
» ack global
fixtures/tools/package-lock.json
171:        "insert-module-globals": "^7.0.0",
602:    "insert-module-globals": {
604:      "resolved": "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-7.2.0.tgz",
src/javascript/tail.js
1:})(typeof global !== "undefined" ? global : typeof window !== "undefined" ? window : this)
src/javascript/head.js
1:(function(global) {
```
