### ISSUE TITLE
TODO: maybe use https://crates.io/crates/vlq instead?

### ISSUE THREAD

**Issue by chee** [Financial-Times/oax#17]
TODO: maybe use https://crates.io/crates/vlq instead?

_Originally posted by @JakeChampion in https://github.com/Financial-Times/oax/pull/15_

**Comment by chee** [comment]
@JakeChampion are we still interested in doing this? they have such different interfaces and this seems to be fine...

**Comment by JakeChampion** [comment]
I tried and failed

**Comment by chee** [comment]
*whistles*
