### ISSUE TITLE
not all bower dependencies have a "bower.json"

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/oax#29]
when bundling npm packages the root manifest is the same as a dependency manifest . -- both being package.json

when bundling bower packages the root manifest is bower.json and a dependency manifest is .bower.json

oax gets by most of the time because a dependency usually has a bower.json file

o-gallery depends on ftscroller which has no bower.json file and currently makes `oax` fail to bundle o-gallery.

**Comment by chee** [comment]
oax should prefer ".bower.json" if it's present
