### ISSUE TITLE
Allow .mjs entry points in bower.json

### ISSUE THREAD

**Issue by chee** [Financial-Times/oax#39]
Should we also allow `.mjs`?

_Originally posted by @JakeChampion in https://github.com/Financial-Times/oax/pull/38#issuecomment-613410124_

**Comment by JakeChampion** [comment]
We likely should allow it, but not require it for understanding that a file is using ECMAScript Modules -- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#Aside_%E2%80%94_.mjs_versus_.js

**Comment by chee** [comment]
i don't think we need to do this because we aren't making .mjs files and this tool is only for us, and will hopefully be retired soon.
