### ISSUE TITLE
implement a test for reproducible bundles

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/oax#8]
We need to have an automated test for #5

**Comment by chee** [comment]
note to self: try a building the same bundle twice in two different directories, and diffing the results

**Comment by JakeChampion** [comment]
How about from different operating systems as well?
@ft/sass has an issue where the sourcemaps generated are different based on the operating system it is running on, which sucks.

**Comment by chee** [comment]
that _does_ suck!

**Comment by chee** [comment]
we actually don't care about this any more. because `scrumple` will not be used in the build service.
